<eclipse>
<message date="0/0/0" time="0.00000000000000">
 Interpolation of Kro/Krg suppressed                                        
</message>
<message date="0/0/0" time="0.00000000000000">
 HCSCAL option deactivated as this is a NOMIX run                           
</message>
<message date="0/0/0" time="0.00000000000000">
 Only fail-safe SAVE files will be generated                                
</message>
<comment date="1/1/1990" time="0.00000000000000">
 Since neither GRIDOPTS or REGDIMS specified in the                         
 Runspec section, the number of FLUXNUM regions will                        
 be set using item 11 of TABDIMS keyword                                    
</comment>
<message date="1/1/1990" time="0.00000000000000">
 The message service has been activated                                     
</message>
<message date="1/1/1990" time="0.00000000000000">
 Checking for licenses                                                      
</message>
<message date="1/1/1990" time="0.00000000000000">
 Checking for licenses                                                      
</message>
<message date="1/1/1990" time="0.00000000000000">
 Checking for licenses                                                      
</message>
<message date="1/1/1990" time="0.00000000000000">
 Checking for licenses                                                      
</message>
<message date="1/1/1990" time="0.00000000000000">
 ECLIPSE license expires        31-Jan-2021                                 
</message>
<message date="1/1/1990" time="0.00000000000000">
 Compositional license expires  31-Jan-2021                                 
</message>
<warning date="1/1/1990" time="0.00000000000000">
 243 values of TOPS out of 324 are undefined. If only first layer of TOPS   
 supplied, values for subsequent layers will be set up first.               
</warning>
<message date="1/1/1990" time="0.00000000000000">
 Processing GRID data                                                       
</message>
<message date="1/1/1990" time="0.00000000000000">
  The WARP linear solver has   1 sub-grids                                  
</message>
<message date="1/1/1990" time="0.00000000000000">
 Model has 324 active cells                                                 
</message>
<message date="1/1/1990" time="0.00000000000000">
 ROCK specified but ROCKOPTS not yet read                                   
 ROCK will default to PVT Region                                            
</message>
<message date="1/1/1990" time="0.00000000000000">
 Processing PROPS data                                                      
</message>
<message date="1/1/1990" time="0.00000000000000">
 Asphaltene modeling switched on                                            
</message>
<message date="1/1/1990" time="0.00000000000000">
 Processing SOLUTION data                                                   
</message>
<message date="1/1/1990" time="0.00000000000000">
 AIM option used                                                            
</message>
<message date="1/1/1990" time="0.00000000000000">
 This run is initialized by equilibration.                                  
 If the TEMPI keyword has been specified, it will be ignored.               
</message>
<message date="1/1/1990" time="0.00000000000000">
 Gas-Oil contact = Oil-Water contact                                        
</message>
<warning date="1/1/1990" time="0.00000000000000">
 Equilibration depth of 7500.000                                            
 is not within range of cell depths,                                        
 which are from 7315.000 to 7475.000                                        
</warning>
<message date="1/1/1990" time="0.00000000000000">
 Compositional equilibration option 1                                       
 Single phase equilibration : total composition specified                   
</message>
<message date="1/1/1990" time="0.00000000000000">
 Datum depth set to 7500.000                                                
</message>
<message date="1/1/1990" time="0.00000000000000">
 VOIL output requested                                                      
</message>
<message date="1/1/1990" time="0.00000000000000">
 Processing SUMMARY data                                                    
</message>
<message date="1/1/1990" time="0.00000000000000">
 355 summary file items requested                                           
 TIME     and YEARS    also available in summary file                       
</message>
<message date="1/1/1990" time="0.00000000000000">
 Run summaries requested                                                    
</message>
<message date="1/1/1990" time="0.00000000000000">
 Starting processing of SCHEDULE section                                    
</message>
<message date="1/1/1990" time="0.00000000000000">
 Control mode GAS      set for well P                                       
</message>
<warning date="1/1/1990" time="0.00000000000000">
 Bottom hole pressure limit not set for well P                              
 Will use default value of 1469.590 Psia                                    
</warning>
<message date="1/1/1990" time="0.00000000000000">
 Control mode GROUP    set for well I                                       
</message>
<message date="30/12/1998" time="3285.00000000000000">
 Replacing existing stage                                                   
</message>
<message date="30/12/1999" time="3650.00000000000000">
 Shutting well I                                                            
</message>
<message date="8/2/2000" time="3690.00000000000000">
 Gas injection mode change in group FIELD from RE to Passive                
</message>
<message date="28/12/2004" time="5475.00000000000000">
 Producing run summaries                                                    
</message>
<message date="28/12/2004" time="5475.00000000000000">
 Run summaries complete                                                     
</message>
</eclipse>
